[project]
name = "acme"
version = "0.0.1"
description = "python template"
readme = ".github/README.md"
requires-python = ">=3.11"
license = { file = "LICENSE" }
dependencies = [
    "clu>=0.0.12",
    "datasets>=4.8.4",
    "einops>=0.8.1",
    "flax>=0.12.6",
    "huggingface-hub>=1.10.2",
    "jaxtyping>=0.3.2",
    "ml-collections>=1.1.0",
    "safetensors>=0.7.0",
    "transformers>=5.7.0",
]

[dependency-groups]
dev = [
    "pytest>=6.0.0",
    "ruff>=0.15.10",
]
wandb = [
    "wandb>=0.20.1",
]

[tool.ruff]
line-length = 90

[tool.ruff.lint]
select = ["E", "F", "I001"]

[tool.ruff.lint.isort]
lines-after-imports = 2

[tool.pytest.ini_options]
testpaths = ["tests"]
filterwarnings = [
    "ignore::DeprecationWarning",
	"ignore::UserWarning"
]

